---
- hosts: localhost
  gather_facts: no
  connection: localhost

  tasks:
    - name: Register the output of the 'uptime' command
      command: uptime
      register: system_uptime  # comment

    - name: Print the registered output of the uptime command
      debug:
        var: system_uptime.stdout

# $ pip3 install yamlint
# $ yamllint .