---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: get system uptime to demo
      command: uptime
      changed_when: false
      register: system_uptime

    - name: Print the registered output of the 'uptime' command.
      debug:
        var: system_uptime.stdout

## $ ansible-lint main.yml